// For anyone needing to take notes on the go. These notes do not save so please make sure you either screenshot it or paste it into another note source.
// This is just easy if you are needing something right then and there. 


//COPY AND PASTE THE FOLLOWING (WITH THE JAVASCRIPT ON IT OR IT WILL NOT WORK)

javascript:(function() {document.body.innerHTML+='<iframe style=\"width: 25%;border: 3px solid black; z-index: 100000000000; 
position: fixed; bottom: 0; right: 0; height: 50%;\" src=\"https://offline-editor--adcharity.repl.co/optimized.html\">';})();
