// This is a Bookmarklet that you can use to make your current tab. A Cute Face :) Let me know in the discord server. (link in my bio) What other faces you want.
// It is a Random generation of the faces so you will be suprised at what you get.

javascript: const faces = ['OwO', 'UwU', 'TwT', '>w<', '^w^', '◑﹏◐', '(?_?)', '(⊙﹏⊙)', 'o(≧o≦)o', '↖(^ω^)↗']; let face = faces
[Math.floor(Math.random()*faces.length)]; document.write('<body style=\'background-color: black;\'></body><title>' +
face + '</title><p style=\'text-align: center; font-size: 500px; font-family: Arial; color: white;\'>' + face + '</p>');
